# Danh sách 100 mã cổ phiếu VN100
# Cập nhật theo rổ VN100 mới nhất

VN100_SYMBOLS = [
    # VN30 - Top 30 blue chips
    "ACB", "BCM", "BID", "BVH", "CTG", "FPT", "GAS", "GVR", "HDB", "HPG",
    "MBB", "MSN", "MWG", "PLX", "POW", "SAB", "SHB", "SSB", "SSI", "STB",
    "TCB", "TPB", "VCB", "VHM", "VIB", "VIC", "VJC", "VNM", "VPB", "VRE",
    
    # VN70 - Next 70 stocks
    "ANV", "ASM", "BAF", "BMP", "BSI", "BWE", "CII", "CMG", "CNG", "CTD",
    "DCM", "DGC", "DGW", "DIG", "DPM", "DRC", "DXG", "DXS", "EIB", "EVF",
    "FRT", "GEX", "GMD", "HAG", "HCM", "HDC", "HDG", "HHV", "HSG", "HT1",
    "IMP", "KBC", "KDC", "KDH", "KOS", "LPB", "MSB", "NAB", "NKG", "NLG",
    "NT2", "NVL", "OCB", "PAN", "PC1", "PDR", "PET", "PHR", "PNJ", "PPC",
    "PTB", "PVD", "PVS", "PVT", "REE", "SBT", "SCS", "SHI", "SIP", "SJS",
    "SKG", "SZC", "TCH", "TLG", "TNH", "VCG", "VCI", "VGC", "VHC", "VND",
]

# Thông tin chi tiết các mã (sẽ được cập nhật từ API)
VN100_INFO = {
    "ACB": {"name": "Ngân hàng TMCP Á Châu", "exchange": "HOSE", "industry": "Ngân hàng"},
    "BCM": {"name": "Tổng Công ty Đầu tư và Phát triển Công nghiệp", "exchange": "HOSE", "industry": "Bất động sản"},
    "BID": {"name": "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "BVH": {"name": "Tập đoàn Bảo Việt", "exchange": "HOSE", "industry": "Bảo hiểm"},
    "CTG": {"name": "Ngân hàng TMCP Công Thương Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "FPT": {"name": "Công ty Cổ phần FPT", "exchange": "HOSE", "industry": "Công nghệ"},
    "GAS": {"name": "Tổng Công ty Khí Việt Nam", "exchange": "HOSE", "industry": "Dầu khí"},
    "GVR": {"name": "Tập đoàn Công nghiệp Cao su Việt Nam", "exchange": "HOSE", "industry": "Cao su"},
    "HDB": {"name": "Ngân hàng TMCP Phát triển TP.HCM", "exchange": "HOSE", "industry": "Ngân hàng"},
    "HPG": {"name": "Công ty Cổ phần Tập đoàn Hòa Phát", "exchange": "HOSE", "industry": "Thép"},
    "MBB": {"name": "Ngân hàng TMCP Quân đội", "exchange": "HOSE", "industry": "Ngân hàng"},
    "MSN": {"name": "Công ty Cổ phần Tập đoàn Masan", "exchange": "HOSE", "industry": "Hàng tiêu dùng"},
    "MWG": {"name": "Công ty Cổ phần Đầu tư Thế Giới Di Động", "exchange": "HOSE", "industry": "Bán lẻ"},
    "PLX": {"name": "Tập đoàn Xăng Dầu Việt Nam", "exchange": "HOSE", "industry": "Dầu khí"},
    "POW": {"name": "Tổng Công ty Điện lực Dầu khí Việt Nam", "exchange": "HOSE", "industry": "Điện"},
    "SAB": {"name": "Tổng Công ty Cổ phần Bia - Rượu - Nước giải khát Sài Gòn", "exchange": "HOSE", "industry": "Đồ uống"},
    "SHB": {"name": "Ngân hàng TMCP Sài Gòn - Hà Nội", "exchange": "HOSE", "industry": "Ngân hàng"},
    "SSB": {"name": "Ngân hàng TMCP Đông Nam Á", "exchange": "HOSE", "industry": "Ngân hàng"},
    "SSI": {"name": "Công ty Cổ phần Chứng khoán SSI", "exchange": "HOSE", "industry": "Chứng khoán"},
    "STB": {"name": "Ngân hàng TMCP Sài Gòn Thương Tín", "exchange": "HOSE", "industry": "Ngân hàng"},
    "TCB": {"name": "Ngân hàng TMCP Kỹ Thương Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "TPB": {"name": "Ngân hàng TMCP Tiên Phong", "exchange": "HOSE", "industry": "Ngân hàng"},
    "VCB": {"name": "Ngân hàng TMCP Ngoại thương Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "VHM": {"name": "Công ty Cổ phần Vinhomes", "exchange": "HOSE", "industry": "Bất động sản"},
    "VIB": {"name": "Ngân hàng TMCP Quốc tế Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "VIC": {"name": "Tập đoàn Vingroup", "exchange": "HOSE", "industry": "Bất động sản"},
    "VJC": {"name": "Công ty Cổ phần Hàng không Vietjet", "exchange": "HOSE", "industry": "Hàng không"},
    "VNM": {"name": "Công ty Cổ phần Sữa Việt Nam", "exchange": "HOSE", "industry": "Thực phẩm"},
    "VPB": {"name": "Ngân hàng TMCP Việt Nam Thịnh Vượng", "exchange": "HOSE", "industry": "Ngân hàng"},
    "VRE": {"name": "Công ty Cổ phần Vincom Retail", "exchange": "HOSE", "industry": "Bất động sản"},
    # VN70
    "ANV": {"name": "Công ty Cổ phần Nam Việt", "exchange": "HOSE", "industry": "Thủy sản"},
    "ASM": {"name": "Công ty Cổ phần Tập đoàn Sao Mai", "exchange": "HOSE", "industry": "Bất động sản"},
    "BAF": {"name": "Công ty Cổ phần Nông nghiệp BaF Việt Nam", "exchange": "HOSE", "industry": "Nông nghiệp"},
    "BMP": {"name": "Công ty Cổ phần Nhựa Bình Minh", "exchange": "HOSE", "industry": "Nhựa"},
    "BSI": {"name": "Công ty Cổ phần Chứng khoán BIDV", "exchange": "HOSE", "industry": "Chứng khoán"},
    "BWE": {"name": "Công ty Cổ phần Nước - Môi trường Bình Dương", "exchange": "HOSE", "industry": "Tiện ích"},
    "CII": {"name": "Công ty Cổ phần Đầu tư Hạ tầng Kỹ thuật TP.HCM", "exchange": "HOSE", "industry": "Hạ tầng"},
    "CMG": {"name": "Công ty Cổ phần Tập đoàn Công nghệ CMC", "exchange": "HOSE", "industry": "Công nghệ"},
    "CNG": {"name": "Công ty Cổ phần CNG Việt Nam", "exchange": "HOSE", "industry": "Dầu khí"},
    "CTD": {"name": "Công ty Cổ phần Xây dựng Coteccons", "exchange": "HOSE", "industry": "Xây dựng"},
    "DCM": {"name": "Công ty Cổ phần Phân bón Dầu khí Cà Mau", "exchange": "HOSE", "industry": "Hóa chất"},
    "DGC": {"name": "Công ty Cổ phần Tập đoàn Hóa chất Đức Giang", "exchange": "HOSE", "industry": "Hóa chất"},
    "DGW": {"name": "Công ty Cổ phần Thế Giới Số", "exchange": "HOSE", "industry": "Công nghệ"},
    "DIG": {"name": "Tổng Công ty Cổ phần Đầu tư Phát triển Xây dựng", "exchange": "HOSE", "industry": "Bất động sản"},
    "DPM": {"name": "Tổng Công ty Phân bón và Hóa chất Dầu khí", "exchange": "HOSE", "industry": "Hóa chất"},
    "DRC": {"name": "Công ty Cổ phần Cao su Đà Nẵng", "exchange": "HOSE", "industry": "Cao su"},
    "DXG": {"name": "Công ty Cổ phần Tập đoàn Đất Xanh", "exchange": "HOSE", "industry": "Bất động sản"},
    "DXS": {"name": "Công ty Cổ phần Dịch vụ Bất động sản Đất Xanh", "exchange": "HOSE", "industry": "Bất động sản"},
    "EIB": {"name": "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "EVF": {"name": "Công ty Tài chính Cổ phần Điện lực", "exchange": "HOSE", "industry": "Tài chính"},
    "FRT": {"name": "Công ty Cổ phần Bán lẻ Kỹ thuật số FPT", "exchange": "HOSE", "industry": "Bán lẻ"},
    "GEX": {"name": "Tổng Công ty Cổ phần Thiết bị Điện Việt Nam", "exchange": "HOSE", "industry": "Điện"},
    "GMD": {"name": "Công ty Cổ phần Gemadept", "exchange": "HOSE", "industry": "Logistics"},
    "HAG": {"name": "Công ty Cổ phần Hoàng Anh Gia Lai", "exchange": "HOSE", "industry": "Nông nghiệp"},
    "HCM": {"name": "Công ty Cổ phần Chứng khoán TP.HCM", "exchange": "HOSE", "industry": "Chứng khoán"},
    "HDC": {"name": "Công ty Cổ phần Phát triển Nhà Bà Rịa - Vũng Tàu", "exchange": "HOSE", "industry": "Bất động sản"},
    "HDG": {"name": "Công ty Cổ phần Tập đoàn Hà Đô", "exchange": "HOSE", "industry": "Bất động sản"},
    "HHV": {"name": "Công ty Cổ phần Đầu tư Hạ tầng Giao thông Đèo Cả", "exchange": "HOSE", "industry": "Hạ tầng"},
    "HSG": {"name": "Công ty Cổ phần Tập đoàn Hoa Sen", "exchange": "HOSE", "industry": "Thép"},
    "HT1": {"name": "Công ty Cổ phần Xi măng Hà Tiên 1", "exchange": "HOSE", "industry": "Vật liệu xây dựng"},
    "IMP": {"name": "Công ty Cổ phần Dược phẩm Imexpharm", "exchange": "HOSE", "industry": "Dược phẩm"},
    "KBC": {"name": "Tổng Công ty Phát triển Đô thị Kinh Bắc", "exchange": "HOSE", "industry": "Bất động sản"},
    "KDC": {"name": "Công ty Cổ phần Tập đoàn KIDO", "exchange": "HOSE", "industry": "Thực phẩm"},
    "KDH": {"name": "Công ty Cổ phần Đầu tư Kinh doanh Nhà Khang Điền", "exchange": "HOSE", "industry": "Bất động sản"},
    "KOS": {"name": "Công ty Cổ phần KOSY", "exchange": "HOSE", "industry": "Bất động sản"},
    "LPB": {"name": "Ngân hàng TMCP Bưu điện Liên Việt", "exchange": "HOSE", "industry": "Ngân hàng"},
    "MSB": {"name": "Ngân hàng TMCP Hàng Hải Việt Nam", "exchange": "HOSE", "industry": "Ngân hàng"},
    "NAB": {"name": "Ngân hàng TMCP Nam Á", "exchange": "HOSE", "industry": "Ngân hàng"},
    "NKG": {"name": "Công ty Cổ phần Thép Nam Kim", "exchange": "HOSE", "industry": "Thép"},
    "NLG": {"name": "Công ty Cổ phần Đầu tư Nam Long", "exchange": "HOSE", "industry": "Bất động sản"},
    "NT2": {"name": "Công ty Cổ phần Điện lực Dầu khí Nhơn Trạch 2", "exchange": "HOSE", "industry": "Điện"},
    "NVL": {"name": "Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va", "exchange": "HOSE", "industry": "Bất động sản"},
    "OCB": {"name": "Ngân hàng TMCP Phương Đông", "exchange": "HOSE", "industry": "Ngân hàng"},
    "PAN": {"name": "Công ty Cổ phần Tập đoàn PAN", "exchange": "HOSE", "industry": "Nông nghiệp"},
    "PC1": {"name": "Công ty Cổ phần Tập đoàn PC1", "exchange": "HOSE", "industry": "Điện"},
    "PDR": {"name": "Công ty Cổ phần Phát triển Bất động sản Phát Đạt", "exchange": "HOSE", "industry": "Bất động sản"},
    "PET": {"name": "Tổng Công ty Cổ phần Dịch vụ Tổng hợp Dầu khí", "exchange": "HOSE", "industry": "Dầu khí"},
    "PHR": {"name": "Công ty Cổ phần Cao su Phước Hòa", "exchange": "HOSE", "industry": "Cao su"},
    "PNJ": {"name": "Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận", "exchange": "HOSE", "industry": "Bán lẻ"},
    "PPC": {"name": "Công ty Cổ phần Nhiệt điện Phả Lại", "exchange": "HOSE", "industry": "Điện"},
    "PTB": {"name": "Công ty Cổ phần Phú Tài", "exchange": "HOSE", "industry": "Vật liệu xây dựng"},
    "PVD": {"name": "Tổng Công ty Cổ phần Khoan và Dịch vụ Khoan Dầu khí", "exchange": "HOSE", "industry": "Dầu khí"},
    "PVS": {"name": "Tổng Công ty Cổ phần Dịch vụ Kỹ thuật Dầu khí Việt Nam", "exchange": "HNX", "industry": "Dầu khí"},
    "PVT": {"name": "Tổng Công ty Cổ phần Vận tải Dầu khí", "exchange": "HOSE", "industry": "Vận tải"},
    "REE": {"name": "Công ty Cổ phần Cơ Điện Lạnh", "exchange": "HOSE", "industry": "Điện"},
    "SBT": {"name": "Công ty Cổ phần Thành Thành Công - Biên Hòa", "exchange": "HOSE", "industry": "Thực phẩm"},
    "SCS": {"name": "Công ty Cổ phần Dịch vụ Hàng hóa Sài Gòn", "exchange": "HOSE", "industry": "Logistics"},
    "SHI": {"name": "Công ty Cổ phần Quốc tế Sơn Hà", "exchange": "HOSE", "industry": "Sản xuất"},
    "SIP": {"name": "Công ty Cổ phần Đầu tư Sài Gòn VRG", "exchange": "HOSE", "industry": "Bất động sản"},
    "SJS": {"name": "Công ty Cổ phần Đầu tư Phát triển Đô thị và Khu công nghiệp Sông Đà", "exchange": "HOSE", "industry": "Bất động sản"},
    "SKG": {"name": "Công ty Cổ phần Tập đoàn Superdong - Kiên Giang", "exchange": "HOSE", "industry": "Vận tải"},
    "SZC": {"name": "Công ty Cổ phần Sonadezi Châu Đức", "exchange": "HOSE", "industry": "Bất động sản"},
    "TCH": {"name": "Công ty Cổ phần Đầu tư Dịch vụ Tài chính Hoàng Huy", "exchange": "HOSE", "industry": "Tài chính"},
    "TLG": {"name": "Công ty Cổ phần Tập đoàn Thiên Long", "exchange": "HOSE", "industry": "Sản xuất"},
    "TNH": {"name": "Công ty Cổ phần Bệnh viện Quốc tế Thái Nguyên", "exchange": "HOSE", "industry": "Y tế"},
    "VCG": {"name": "Tổng Công ty Cổ phần Xuất nhập khẩu và Xây dựng Việt Nam", "exchange": "HOSE", "industry": "Xây dựng"},
    "VCI": {"name": "Công ty Cổ phần Chứng khoán Bản Việt", "exchange": "HOSE", "industry": "Chứng khoán"},
    "VGC": {"name": "Tổng Công ty Viglacera", "exchange": "HOSE", "industry": "Vật liệu xây dựng"},
    "VHC": {"name": "Công ty Cổ phần Vĩnh Hoàn", "exchange": "HOSE", "industry": "Thủy sản"},
    "VND": {"name": "Công ty Cổ phần Chứng khoán VNDirect", "exchange": "HOSE", "industry": "Chứng khoán"},
}

def get_vn100_symbols():
    """Trả về danh sách 100 mã VN100"""
    return VN100_SYMBOLS

def get_vn100_info():
    """Trả về thông tin chi tiết các mã VN100"""
    return VN100_INFO
